### PR TITLE
PostgreSQL implementation

### PR DESCRIPTION
**Pull request by andrewmichaelsmith**
Hi

Please consider this a request for feedback rather than a final pull request. 

It is a working implementation, but I have some tidying up left to do, I just want to check if this is something you'd be interested in merging first.

Left to do (from my point of view):

* Add tests
* The "capabilities ending in s are ssl" messes up my naming (postgres vs postgre). Happy to include in this a change whereby capabilities explicitly set "ssl: True" if that's the direction you would like to take?
* Some tidying up of the parsing.

You can test this using `psql`, for example:

```
psql postgres://username:password123@localhost:5432/database
```

"username" and "password123" will be logged.

### CODE REVIEW

**Comment by johnnykv** [comment]
Looks good, cool to have this capability. I think we stick with the naming "postgre" for now... I do see the issue with the ssl wrapping - but let's keep that out of this pr.

Looking forward to seeing a few test cases :-)

**Comment by andrewmichaelsmith** [comment]
@johnnykv updated

- shuffled code a bit to make it neater, handle unexpected requests
- added a testcase, i'm just using a standard postgres client
- renamed to postgresql, the "official" name (https://wiki.postgresql.org/wiki/ProjectName)

**Comment by johnnykv** [comment]
Looks good. Did you test it with hydra?

**Comment by andrewmichaelsmith** [comment]
Thanks! I hadn't test with hydra, but I have now:

```
$ hydra -l postgres -P 10k_most_common.txt postgres://localhost:5432
Hydra v8.1 (c) 2014 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (http://www.thc.org/thc-hydra) starting at 2017-10-09 20:15:33
[DATA] max 16 tasks per 1 server, overall 64 tasks, 10000 login tries (l:1/p:10000), ~9 tries per task
[DATA] attacking service postgres on port 5432
1 of 1 target completed, 0 valid passwords found
Hydra (http://www.thc.org/thc-hydra) finished at 2017-10-09 20:15:56
```
```
$ wc -l heralding_activity.log 
10001 heralding_activity.log
```

**Comment by andrewmichaelsmith** [comment]
Awesome, thanks for the project, was a breeze to integrate with :)

**Pull request merged**
