### PR TITLE
Fix RDP Connection issue in some MSRDP clients

### PR DESCRIPTION
**Pull request by realsdx**
The cookie handling method of `x224ConnectionRequestPDU` was wrong.
This PR corrects it.

### CODE REVIEW

**Comment by johnnykv** [comment]
Which specific bug from which client did this PR fix?

**Comment by realsdx** [comment]
The cookie field in `x224ConnectionRequestPDU` in is optional, earlier it was assuming that as a mandatory field.

**Comment by johnnykv** [comment]
At least on Win 10 I see the error that @ariadarkkkis mentions [1]
[1] https://github.com/johnnykv/heralding/issues/125#issuecomment-581691697

**Comment by realsdx** [comment]
i haven't tested it with latest windows 10 build, will do ASAP.

**Comment by realsdx** [comment]
The problem in win10 is due to some cryptographic error. Can't say what is it rn. will check the raw bytes in packets.

**Comment by realsdx** [comment]
I think i found the fix! Will tet further and update the PR

**Comment by realsdx** [comment]
@johnnykv Can you please test it again with the win 10 build?

**Comment by johnnykv** [comment]
Seems to work when providing credentials beforehand:

`2020-03-01 13:22:30,339 (heralding.misc.session) rdp authentication attempt from 192.168.87.104:49742. Auth mechanism: plaintext, session id 2aa1a510-703c-4d91-8bab-ffb98e62475b Credentials: {"username": "jame", "password": "bond"}`

If we want to provide support for providing credentials AFTER the connect, we also needs to send a loginscreen - this will be out of scope (currently) for heralding.

**Pull request merged**
