### PR TITLE
Add Dockerfile, Update Readme & Add Docker guide

### PR DESCRIPTION
**Pull request by jjasonkal**
It is easier to run and test Heralding with Docker as it is simple, consistent and efficient.

Changes proposed in this pull request:
- Add Multistage Dockerfile in order to have small image size.
- Add guide for building Docker image in main Readme.

### CODE REVIEW

**Comment by johnnykv** [comment]
Great, thanks. Regarding the md document. Could the information be condensed and put into the main readme file?

**Comment by jjasonkal** [comment]
Of course, I will do it

**Comment by jjasonkal** [comment]
If the pull request is accepted ,i suggest that you push the official Heralding docker image to Docker Hub.

**Comment by jjasonkal** [comment]
I see no activity in the pr, is there anything that i should change? @johnnykv

**Comment by johnnykv** [comment]
Sorry, did not see your latest commit. Will merge now.

**Pull request merged**
